# Copyright 2020 RIFT Inc
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: {{ .Values.global.namespace.name }}
data:
  bind-http:
    {{ .Values.bindPort.http }}
  bind-https:
    {{ .Values.bindPort.https }}
  config-frontend: |
    http-response replace-header Set-Cookie (.*) \1;\ Secure
  config-backend: |
    timeout server 500s
