# Copyright 2020 RIFT Inc
# Copyright 2021 DZS Inc
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rw-nats
  namespace: {{ .Values.global.namespace.name }}
  labels:
    app: rw.nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rw.nats
  template:
    metadata:
      labels:
        app: rw.nats
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        {{ if .Values.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{ else }}
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
        {{- end }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: nats-exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: rwnats-exp
              containerPort: 7777
              protocol: TCP

          command:
          - prometheus-nats-exporter
          args:
            - -connz
            - -varz
            - -subz
            - "http://localhost:8444"

        - name: nats
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: rwnats
              containerPort: 4222
              protocol: TCP

          command:
          - /nats-server
          args: ["--config", "/config/rw-nats.conf", "-m", "8444"]

          volumeMounts:
          - name: rw-nats-config
            mountPath: /config
            readOnly: false

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: rw-nats-config
          configMap:
            name: rw-nats-config
