---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-5g-free-go35xzika-0-0-3-hr
  namespace: default
spec:
  chart:
    spec:
      chart: ./de-5g-free-go35xzika-0-0-3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: de-5g-free-go35xzika-0-0-3-source
  interval: 5m0s
  releaseName: de-5g-free-go35xzika-0-0-3
  values:
    db:
      enabled: true
    global:
      nrf:
        service:
          name: nrf-nnrf
          nodePort: "30800"
          port: "8000"
          type: ClusterIP
      projectName: free5gc
      sbi:
        scheme: http
    initcontainers:
      busybox:
        image: busybox
        tag: 1.32.0
      curl:
        image: initcurl
        registry: towards5gs
        tag: 1.0.0
    mongodb:
      auth:
        enabled: false
      fullnameOverride: mongodb
      persistence:
        mountPath: /bitnami/mongodb/data/db/
        size: 6Gi
      service:
        name: mongodb
        nodePort: "30017"
        port: 27017
        type: ClusterIP
      useStatefulSet: true
    nrf:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: nrf-configmap
      configuration:
        configuration: |-
          DefaultPlmnId:
            mcc: 208
            mnc: 93
          serviceNameList:
            - nnrf-nfm
            - nnrf-disc
        logger:
          MongoDBLibrary:
            ReportCaller: false
            debugLevel: info
          NRF:
            ReportCaller: false
            debugLevel: info
          OpenApi:
            ReportCaller: false
            debugLevel: info
          PathUtil:
            ReportCaller: false
            debugLevel: info
      image:
        name: towards5gs/free5gc-nrf
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      ingress:
        annotations: {}
        enabled: false
        hosts:
        - host: chart-example.local
          paths: []
        tls: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      name: nrf
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext: {}
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: nrf-volume

