---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-cpl-free-bpyglle7e-0-0-8-hr
  namespace: default
spec:
  chart:
    spec:
      chart: ./de-cpl-free-bpyglle7e-0-0-8
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: de-cpl-free-9ejqnq6v0-0-0-5-source
  interval: 5m0s
  releaseName: de-cpl-free-bpyglle7e-0-0-8
  values:
    db:
      enabled: false
    global:
      nrf:
        service:
          name: nrf-nnrf
          nodePort: "30800"
          port: "8000"
          type: ClusterIP
      projectName: free5gc
      sbi:
        scheme: http
    initcontainers:
      busybox:
        image: busybox
        tag: 1.32.0
      curl:
        image: initcurl
        registry: towards5gs
        tag: 1.0.0
    mongodb:
      service:
        name: mongodb
        nodePort: "30017"
        port: 27017
        type: ClusterIP
    webui:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: webui-configmap
      configuration:
        logger:
          MongoDBLibrary:
            ReportCaller: false
            debugLevel: info
          OpenApi:
            ReportCaller: false
            debugLevel: info
          PathUtil:
            ReportCaller: false
            debugLevel: info
          WEBUI:
            ReportCaller: true
            debugLevel: info
      image:
        name: towards5gs/free5gc-webui
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      ingress:
        annotations: {}
        enabled: false
        hosts:
        - host: chart-example.local
          paths: []
        tls: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      name: webui
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext: {}
      service:
        name: webui-service
        nodePort: 30599
        port: 5000
        type: NodePort
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: webui-volume

