---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-cp4-free-le7yscxy5-0-0-6-hr
  namespace: default
spec:
  chart:
    spec:
      chart: ./de-cp4-free-le7yscxy5-0-0-6
      sourceRef:
        kind: GitRepository
        name: de-cp4-free-le7yscxy5-0-0-6-source
  interval: 5m0s
  releaseName: de-cp4-free-le7yscxy5-0-0-6
  values:
    amf:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: amf-configmap
      configuration:
        configuration: "amfName: AMF\nserviceNameList:\n  - namf-comm\n  - namf-evts\n
          \ - namf-mt\n  - namf-loc\n  - namf-oam\nservedGuamiList:\n  - plmnId:\n
          \     mcc: 208\n      mnc: 93\n    amfId: cafe00\nsupportTaiList:\n  - plmnId:\n
          \     mcc: 208\n      mnc: 93\n    tac: 1\nplmnSupportList:\n  - plmnId:\n
          \     mcc: 208\n      mnc: 93\n    snssaiList:\n      - sst: 1\n        sd:
          010203\n      - sst: 1\n        sd: 112233\nsupportDnnList:\n  - internet\nsecurity:\n
          \ integrityOrder:\n    - NIA2\n  cipheringOrder:\n    - NEA0\nnetworkName:\n
          \ full: free5GC\n  short: free      \nlocality: area1 # Name of the location
          where a set of AMF, SMF and UPFs are located\nnetworkFeatureSupport5GS:
          # 5gs Network Feature Support IE, refer to TS 24.501\n  enable: true # append
          this IE in Registration accept or not\n  imsVoPS: 0 # IMS voice over PS
          session indicator (uinteger, range: 0~1)\n  emc: 0 # Emergency service support
          indicator for 3GPP access (uinteger, range: 0~3)\n  emf: 0 # Emergency service
          fallback indicator for 3GPP access (uinteger, range: 0~3)\n  iwkN26: 0 #
          Interworking without N26 interface indicator (uinteger, range: 0~1)\n  mpsi:
          0 # MPS indicator (uinteger, range: 0~1)\n  emcN3: 0 # Emergency service
          support indicator for Non-3GPP access (uinteger, range: 0~1)\n  mcsi: 0
          # MCS indicator (uinteger, range: 0~1)\nt3502Value: 720\nt3512Value: 3600\nnon3gppDeregistrationTimerValue:
          3240\n# retransmission timer for paging message\nt3513:\n  enable: true
          \    # true or false\n  expireTime: 6s   # default is 6 seconds\n  maxRetryTimes:
          4 # the max number of retransmission\n# retransmission timer for NAS Registration
          Accept message\nt3522:\n  enable: true     # true or false\n  expireTime:
          6s   # default is 6 seconds\n  maxRetryTimes: 4 # the max number of retransmission\n#
          retransmission timer for NAS Registration Accept message\nt3550:\n  enable:
          true     # true or false\n  expireTime: 6s   # default is 6 seconds\n  maxRetryTimes:
          4 # the max number of retransmission\n# retransmission timer for NAS Authentication
          Request/Security Mode Command message\nt3560:\n  enable: true     # true
          or false\n  expireTime: 6s   # default is 6 seconds\n  maxRetryTimes: 4
          # the max number of retransmission\n# retransmission timer for NAS Notification
          message\nt3565:\n  enable: true     # true or false\n  expireTime: 6s   #
          default is 6 seconds\n  maxRetryTimes: 4 # the max number of retransmission"
        logger:
          AMF:
            ReportCaller: false
            debugLevel: info
          Aper:
            ReportCaller: false
            debugLevel: info
          FSM:
            ReportCaller: false
            debugLevel: info
          NAS:
            ReportCaller: false
            debugLevel: info
          NGAP:
            ReportCaller: false
            debugLevel: info
          OpenApi:
            ReportCaller: false
            debugLevel: info
          PathUtil:
            ReportCaller: false
            debugLevel: info
      image:
        name: towards5gs/free5gc-amf
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      ingress:
        annotations: {}
        enabled: false
        hosts:
        - host: chart-example.local
          paths: []
        tls: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      name: amf
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 150m
          memory: 128Mi
        requests:
          cpu: 150m
          memory: 128Mi
      securityContext: {}
      service:
        name: amf-namf
        port: 80
        type: ClusterIP
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: amf-volume
    global:
      amf:
        n2if:
          ipAddress: 10.100.50.249
        service:
          ngap:
            enabled: false
            name: amf-n2
            nodeport: 31412
            port: 38412
            protocol: TCP
            type: NodePort
      n2network:
        cidr: 29
        excludeIP: 10.100.50.254
        gatewayIP: 10.100.50.254
        masterIf: ens2f0
        name: n2network
        subnetIP: 10.100.50.248
      nrf:
        service:
          name: nrf-nnrf
          nodePort: "30800"
          port: "8000"
          type: ClusterIP
      projectName: free5gc
      sbi:
        scheme: http
    initcontainers:
      busybox:
        image: busybox
        tag: 1.32.0
      curl:
        image: initcurl
        registry: towards5gs
        tag: 1.0.0
    mongodb:
      service:
        name: mongodb
        nodePort: "30017"
        port: 27017
        type: ClusterIP

