---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-cp--free-2u0ahcbto-0-0-7-hr
  namespace: default
spec:
  chart:
    spec:
      chart: ./de-cp--free-2u0ahcbto-0-0-7
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: de-cp--free-2u0ahcbto-0-0-7-source
  interval: 5m0s
  releaseName: de-cp--free-2u0ahcbto-0-0-7
  values:
    global:
      n4network:
        cidr: 29
        excludeIP: 10.100.50.246
        gatewayIP: 10.100.50.246
        masterIf: ens2f0
        name: n4network
        subnetIP: 10.100.50.240
      nrf:
        service:
          name: nrf-nnrf
          nodePort: "30800"
          port: "8000"
          type: ClusterIP
      projectName: free5gc
      sbi:
        scheme: http
      smf:
        n4if:
          ipAddress: 10.100.50.244
      userPlaneArchitecture: single
    initcontainers:
      busybox:
        image: busybox
        tag: 1.32.0
      curl:
        image: initcurl
        registry: towards5gs
        tag: 1.0.0
    mongodb:
      service:
        name: mongodb
        nodePort: "30017"
        port: 27017
        type: ClusterIP
    smf:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: smf-configmap
      configuration:
        configuration: "smfName: SMF\nserviceNameList:\n  - nsmf-pdusession\n  - nsmf-event-exposure\n
          \ - nsmf-oam\nsnssaiInfos:\n  - sNssai:\n      sst: 1\n      sd: 010203\n
          \   dnnInfos: # DNN information list\n      - dnn: internet # Data Network
          Name\n        dns: # the IP address of DNS\n          ipv4: 8.8.8.8\n  -
          sNssai:\n      sst: 1\n      sd: 112233\n    dnnInfos: # DNN information
          list\n      - dnn: internet # Data Network Name\n        dns: # the IP address
          of DNS\n          ipv4: 8.8.8.8\n  - sNssai:\n      sst: 2\n      sd: 112234
          \   \n    dnnInfos:\n      - dnn: internet\n        dns: \n          ipv4:
          8.8.8.8\nplmnList: # the list of PLMN IDs that this SMF belongs to (optional,
          remove this key when unnecessary)\n  - mcc: \"208\" # Mobile Country Code
          (3 digits string, digit: 0~9)\n    mnc: \"93\" # Mobile Network Code (2
          or 3 digits string, digit: 0~9)\nuserplane_information: # list of userplane
          information\n  up_nodes: # information of userplane node (AN or UPF)\n    gNB1:
          # the name of the node\n      type: AN # the type of the node (AN or UPF)\n
          \   UPF:  # the name of the node\n      type: UPF # the type of the node
          (AN or UPF)\n      node_id: 10.100.50.241 # the IP/FQDN of N4 interface
          on this UPF (PFCP)\n      sNssaiUpfInfos: # S-NSSAI information list for
          this UPF\n            - sNssai: # S-NSSAI (Single Network Slice Selection
          Assistance Information)\n                sst: 1 # Slice/Service Type (uinteger,
          range: 0~255)\n                sd: 010203 # Slice Differentiator (3 bytes
          hex string, range: 000000~FFFFFF)\n              dnnUpfInfoList: # DNN information
          list for this S-NSSAI\n                - dnn: internet\n                  pools:\n
          \                   - cidr: 10.1.0.0/17\n            - sNssai: # S-NSSAI
          (Single Network Slice Selection Assistance Information)\n                sst:
          1 # Slice/Service Type (uinteger, range: 0~255)\n                sd: 112233
          # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)\n              dnnUpfInfoList:
          # DNN information list for this S-NSSAI\n                - dnn: internet\n
          \                 pools:\n                    - cidr: 10.1.128.0/17 \n      interfaces:
          # Interface list for this UPF\n            - interfaceType: N3 # the type
          of the interface (N3 or N9)\n              endpoints: # the IP address of
          this N3/N9 interface on this UPF\n                - 10.100.50.233\n              networkInstance:
          internet # Data Network Name (DNN)\n  links: # the topology graph of userplane,
          A and B represent the two nodes of each link\n    - A: gNB1\n      B: UPF\nlocality:
          area1 # Name of the location where a set of AMF, SMF and UPFs are located"
        logger:
          Aper:
            ReportCaller: false
            debugLevel: info
          NAS:
            ReportCaller: false
            debugLevel: info
          NGAP:
            ReportCaller: false
            debugLevel: info
          OpenApi:
            ReportCaller: false
            debugLevel: info
          PFCP:
            ReportCaller: false
            debugLevel: info
          PathUtil:
            ReportCaller: false
            debugLevel: info
          SMF:
            ReportCaller: false
            debugLevel: info
        ueRoutingInfo: |-
          UE1: # Group Name
            members:
            - imsi-208930000000003 # Subscription Permanent Identifier of the UE
            topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
            # default path derived from this topology
            # node name should be consistent with smfcfg.yaml
              - A: gNB1
                B: BranchingUPF
              - A: BranchingUPF
                B: AnchorUPF1
            specificPath:
              - dest: 10.100.100.26/32 # the destination IP address on Data Network (DN)
                # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
                # The UPF's name should be consistent with smfcfg.yaml
                path: [BranchingUPF, AnchorUPF2]

          UE2: # Group Name
            members:
            - imsi-208930000000004 # Subscription Permanent Identifier of the UE
            topology: # Network topology for this group (Uplink: A->B, Downlink: B->A)
            # default path derived from this topology
            # node name should be consistent with smfcfg.yaml
              - A: gNB1
                B: BranchingUPF
              - A: BranchingUPF
                B: AnchorUPF1
            specificPath:
              - dest: 10.100.100.16/32 # the destination IP address on Data Network (DN)
                # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
                # The UPF's name should be consistent with smfcfg.yaml
                path: [BranchingUPF, AnchorUPF2]
      image:
        name: towards5gs/free5gc-smf
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      ingress:
        annotations: {}
        enabled: false
        hosts:
        - host: chart-example.local
          paths: []
        tls: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      name: smf
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext: {}
      service:
        name: smf-nsmf
        port: 80
        type: ClusterIP
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: smf-volume

