---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: de-cp--free-a6azfectn-0-0-3-source
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/pradulmt/bm1-helm

