---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dt-cp--free-y3kvxnczn-0-0-7-source
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/pradulmt/bm1-helm

