# Default values for loki.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
image:
  repository: grafana/loki
  tag: 1.6.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3100

nodeSelector: {}

tolerations: []

affinity: {}
