{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
secrets:
  - name: {{ template "mongodb.fullname" . }}
{{- end }}
