# Copyright 2020 RIFT Inc
apiVersion: v1
kind: ConfigMap
metadata:
  name: rw-mongo-config
  namespace: {{ .Values.global.namespace.name }}
data:
  rw-mongo.conf: |
    systemLog:
      destination: file
      path: "/opt/bitnami/mongodb/logs/mongodb.log"
      logAppend: true
      logRotate: reopen
      traceAllExceptions: true
      timeStampFormat: iso8601-utc
    processManagement:
      fork: false
      pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid"
    net:
      bindIp: 0.0.0.0
      port: 27017
    security:
      authorization: disabled
    storage:
      dbPath: "/data"
      journal:
        enabled: true
      wiredTiger:
        engineConfig:
          cacheSizeGB: 3
    setParameter:
      enableLocalhostAuthBypass: true
