# Copyright 2020-2021 RIFT Inc
# Copyright 2021 DZS Inc
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rw-launchpad
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
  namespace: {{ .Values.global.namespace.name }}
spec:
  selector:
    matchLabels:
      {{- include "launchpad.selectorLabels" . | nindent 6 }}
  replicas: 1
  serviceName: {{ include "launchpad.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "launchpad.selectorLabels" . | nindent 8 }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        {{ if .Values.launchpad.image.imagePullSecrets }}
        {{- toYaml .Values.launchpad.image.imagePullSecrets | nindent 8 }}
        {{ else }}
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
        {{- end }}

      {{- if .Values.launchpad.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.launchpad.securityContext.runAsUser }}
        runAsGroup: {{ .Values.launchpad.securityContext.runAsGroup }}
        fsGroup: {{ .Values.launchpad.securityContext.fsGroup }}
      {{- end }}

      hostAliases:
      {{- range $i, $value := .Values.global.hostAliases }}
      - ip: {{ $value.ip | quote }}
        hostnames:
        {{- range $value.hostnames }}
        - {{ . }}
        {{- end }}
      {{- end }}

      containers:
      {{- if .Values.loki.enabled }}
      - name: promtail
        image: grafana/promtail:master
        args:
          - "-config.file=/etc/promtail/promtail.yaml"
          - '-client.url={{ .Values.loki.serviceScheme }}://{{ include "loki.fullname" . }}:{{ .Values.loki.servicePort }}/api/prom/push'
        volumeMounts:
        - name: rift-var-root
          mountPath: /usr/rift/var
          readOnly: false
        - name: promtail-config
          mountPath: /etc/promtail
      {{- end }}

      - name: launchpad
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        command: ["bash", "/scripts/start.sh", {{- include "launchpad.coreDir" . -}}]
        env:
        {{- if .Values.launchpad.securityContext.enabled }}
        - name: RIFT_NO_SUDO_REAPER
          value: "1"
        {{- end }}
        - name: RIFT_IMAGE_VERSION
          value: {{ .Values.launchpad.image.tag }}
        - name: RIFT_EXTERNAL_ADDRESS
          value: {{ .Values.externalAddress }}
        - name: RW_PROMETHEUS_SVC_NAME
          value: {{ include "prometheus.fullname" . }}
        - name: RW_ALERTMGR_SVC_NAME
          value: {{ include "alertmgr.fullname" . }}
        - name: RW_LAUNCHPAD_SVC_NAME
          value: {{ include "launchpad.fullname" . }}
        - name: RW_REDIS_SVC_NAME
          value: {{ include "redis.fullname" . }}
        - name: RW_REDTUNNEL_SVC_NAME
          value: {{ include "redis-tunnel.fullname" . }}
        - name: RW_NATS_SVC_NAME
          value: {{ include "nats.fullname" . }}
        - name: RW_MONGODB_SVC_NAME
          value: {{ include "mongodb.fullname" . }}
        - name: RW_HAPROXY_METRICS_SVC_NAME
          value: {{ include "haproxy-metrics.fullname" . }}
        - name: START_FLUXCD_ADAPTOR
          value: {{ .Values.launchpad.fluxcdAdaptor.enabled | quote }}
        - name: FLUXCD_ADAPTOR_PROJECT
          value: {{ .Values.launchpad.fluxcdAdaptor.project }}
        - name: RW_LP_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RW_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- range $name, $value := .Values.launchpad.env }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        {{- with .Values.launchpad.ports }}
        ports:
        {{- range $data := . }}
        - name: {{ $data.name }}
          containerPort: {{ $data.port }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.launchpad.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: 8443
          initialDelaySeconds: 30
          periodSeconds: 10

        volumeMounts:
        {{- with .Values.launchpad.devSetup }}
        - name: localdisk
          mountPath: /localdisk
          readOnly: false
        - name: rift-install
          mountPath: /usr/rift
          readOnly: false
        {{- end }}
        - name: rift-var-root
          mountPath: /usr/rift/var
          readOnly: false
        - name: config-dir
          mountPath: /config
          readOnly: false
        - name: hostid-dir
          mountPath: /hostid
          readOnly: true
        - name: prelaunch-scripts
          mountPath: /scripts
          readOnly: false
        - name: tls-cert
          mountPath: /rift/cert_store
        - name: ca-bundle
          mountPath: /usr/local/share/ca-certificates
          readOnly: false
        - name: trusted-ca
          mountPath: /etc/ssl/certs
          readOnly: false
        securityContext:
          {{- with .Values.launchpad.capabilities }}
          capabilities:
            add:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      - name: primitive-exec
        image: {{ .Values.launchpad.primitiveExec.image.repository -}} : {{- .Values.launchpad.primitiveExec.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.primitiveExec.image.pullPolicy }}
        command: ["bash", "/scripts/side_car.sh"]

        env:
        {{- range $name, $value := .Values.launchpad.env }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        - name: RW_LAUNCHPAD_SVC_NAME
          value: {{ include "launchpad.fullname" . }}
        - name: RW_LP_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RW_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RIFT_VAR_ROOT
          value: "/usr/rift/var/rift"

        volumeMounts:
        - name: rift-var-root
          mountPath: /usr/rift/var/rift/log/cfgmgr
          subPath: rift/log/cfgmgr
          readOnly: false
        - name: rift-var-root
          mountPath: /usr/rift/var/rift/cfgmgr/tmp
          subPath: rift/cfgmgr/tmp
          readOnly: false
        - name: prelaunch-scripts
          mountPath: /scripts
          readOnly: false

      initContainers:
      - name: wait-for-redis
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        env:
        - name: RW_REDIS_SVC_NAME
          value: {{ include "redis.fullname" . }}
        command: ['sh', '-c', 'until nslookup ${RW_REDIS_SVC_NAME}; do echo waiting for Redis; sleep 2; done;']

      - name: wait-for-nats
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        env:
        - name: RW_NATS_SVC_NAME
          value: {{ include "nats.fullname" . }}
        command: ['sh', '-c', 'until nslookup ${RW_NATS_SVC_NAME}; do echo waiting for NATS; sleep 2; done;']

      - name: wait-for-prometheus
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        env:
        - name: RW_PROMETHEUS_SVC_NAME
          value: {{ include "prometheus.fullname" . }}
        command: ['sh', '-c', 'until nslookup ${RW_PROMETHEUS_SVC_NAME}; do echo waiting for Prometheus; sleep 2; done;']

      - name: wait-for-mongo
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        env:
        - name: RW_MONGODB_SVC_NAME
          value: {{ include "mongodb.fullname" . }}
        command: ['sh', '-c', 'until nslookup ${RW_MONGODB_SVC_NAME}; do echo waiting for Mongo; sleep 2; done;']

      - name: wait-for-haproxy
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        env:
        - name: RW_HAPROXY_METRICS_SVC_NAME
          value: {{ include "haproxy-metrics.fullname" . }}
        command: ['sh', '-c', 'until nslookup ${RW_HAPROXY_METRICS_SVC_NAME}; do echo waiting for HAProxy; sleep 2; done;']

      {{- if .Values.launchpad.securityContext.enabled }}
      - name: set-rvr-ownership
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        command: ["chown", "-R", "{{ .Values.launchpad.securityContext.runAsUser }}:{{ .Values.launchpad.securityContext.fsGroup }}", "/usr/rift/var"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: rift-var-root
          mountPath: /usr/rift/var
          readOnly: false

      - name: set-rvr-perm
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        command: ["chmod", "-R", "775", "/usr/rift/var"]
        securityContext:
            runAsUser: 0
        volumeMounts:
        - name: rift-var-root
          mountPath: /usr/rift/var
          readOnly: false
      {{- end }}

      - name: set-ca-bundle
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
          - echo "Copying files from image ca bundle to pod";
            cp --preserve=timestamps -r /etc/ssl/certs/* /etc/ssl/certs_pod;
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: trusted-ca
          mountPath: /etc/ssl/certs_pod
          readOnly: false

      - name: prelaunch
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        command: ["/bin/bash"]
        args: ["-c", "/usr/rift/rift-shell -- python3 /scripts/prelaunch.py"]
        env:
        - name: RIFT_EXTERNAL_ADDRESS
          value: {{ .Values.externalAddress }}
        - name: RIFT_IMAGE_VERSION
          value: {{ .Values.launchpad.image.tag }}
        - name: RW_REDIS_SVC_NAME
          value: {{ include "redis.fullname" . }}
        - name: RW_K8S_NAMESPACE
          value: {{ .Values.global.namespace.name }}
        volumeMounts:
        {{- with .Values.launchpad.devSetup }}
        - name: localdisk
          mountPath: /localdisk
          readOnly: false
        - name: rift-install
          mountPath: /usr/rift
          readOnly: false
        {{- end }}
        - name: rift-var-root
          mountPath: /usr/rift/var
          readOnly: false
        - name: prelaunch-scripts
          mountPath: /scripts
          readOnly: false
        - name: config-dir
          mountPath: /config
          readOnly: false
        - name: hostid-dir
          mountPath: /hostid
          readOnly: true
      nodeSelector:
        {{ if .Values.launchpad.nodeSelector }}
        {{- toYaml .Values.launchpad.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if .Values.launchpad.hostNameSelector }}
        kubernetes.io/hostname: {{ .Values.launchpad.hostNameSelector | quote }}
        {{ end }}
      {{- with .Values.launchpad.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.launchpad.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- with .Values.launchpad.devSetup }}
        - name: localdisk
          hostPath:
            path: /localdisk
            type: Directory
        - name: rift-install
          hostPath:
            path: {{ .riftInstall }}
            type: Directory
      {{- end }}
        - name: prelaunch-scripts
          configMap:
            name: prelaunch
            defaultMode: 0644
        - name: config-dir
          emptyDir: {}
        - name: hostid-dir
          secret:
            secretName: hostid
        - name: tls-cert
          secret:
            secretName: rw-tls-secret
        - name: ca-bundle
          emptyDir: {}
        - name: trusted-ca
          emptyDir: {}
      {{- if .Values.loki.enabled }}
        - name: promtail-config
          configMap:
            name: promtail-config
            defaultMode: 0755
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: rift-var-root
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storage.capacity }}
      storageClassName: {{ .Values.storage.storageClassName }}
