#Copyright 2020 RIFT Inc
#Copyright 2021 DZS Inc
#
{{- define "launchpad-sts-pvc" }}
{{- printf "rift-var-root-%s-0" (include "launchpad.fullname" .) -}}
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-upgrade-job
  namespace: {{ .Values.global.namespace.name }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  template:
    spec:
      {{- if eq (hasPrefix "8.3" .Values.launchpad.upgradeFrom) false}}
      {{- if .Values.launchpad.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.launchpad.securityContext.runAsUser }}
        runAsGroup: {{ .Values.launchpad.securityContext.runAsGroup }}
        fsGroup: {{ .Values.launchpad.securityContext.fsGroup }}
      {{- end }}
      {{- end }}

      containers:
      - name: {{ .Release.Name }}-pre-upgrade-hook
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.upgradeFrom }}
        imagePullPolicy: IfNotPresent

        volumeMounts:
        {{- with .Values.launchpad.devSetup }}
        - name: localdisk
          mountPath: /localdisk
          readOnly: false
        - name: rift-install
          mountPath: /usr/rift
          readOnly: false
        {{- end }}
        - name: rift-var-root
          mountPath: /usr/rift/var
          readOnly: false

        command: ["/bin/bash"]
        args: ["-c", "/usr/rift/rift-shell -- python3 /usr/rift/usr/bin/rw_redis_backup.py --rollback-save --save --config --data --disable_redis_sync"]
        env:
        - name: RW_REDIS_SVC_NAME
          value: {{ include "redis.fullname" . }}
        - name: RW_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

      initContainers:
      {{- if .Values.launchpad.securityContext.enabled }}
      - name: set-rvr-ownership
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.upgradeFrom }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        command: ["chown", "-R", "{{ .Values.launchpad.securityContext.runAsUser }}:{{ .Values.launchpad.securityContext.fsGroup }}", "/usr/rift/var"]
        securityContext:
            runAsUser: 0
        volumeMounts:
        - name: rift-var-root
          mountPath: /usr/rift/var
          readOnly: false

      - name: set-rvr-perm
        image: {{ .Values.launchpad.image.repository -}} : {{- .Values.launchpad.upgradeFrom }}
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
        command: ["chmod", "-R", "775", "/usr/rift/var"]
        securityContext:
            runAsUser: 0
        volumeMounts:
        - name: rift-var-root
          mountPath: /usr/rift/var
          readOnly: false
      {{- end }}

      restartPolicy: Never
      volumes:
      {{- with .Values.launchpad.devSetup }}
        - name: localdisk
          hostPath:
            path: /localdisk
            type: Directory
        - name: rift-install
          hostPath:
            path: {{ .riftInstall }}
            type: Directory
      {{- end }}
        - name: rift-var-root
          persistentVolumeClaim:
            claimName: rift-var-root-rw-launchpad-0

  backoffLimit: 4
  #activeDeadlineSeconds: 200
  ttlSecondsAfterFinished : 100
