# Copyright 2020-2021 RIFT Inc
# Copyright 2021-2022 DZS Inc
{{- $storageClassName := .Values.storage.storageClassName -}}
{{- $capacity := .Values.storage.capacity -}}
{{- $namespace := .Values.global.namespace.name -}}
{{- with .Values.storage.localStore }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $storageClassName }}
  namespace: {{ $namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $storageClassName }}-{{ $namespace }}-var-root-pv-new
  namespace: {{ $namespace }}
spec:
  capacity:
    storage: {{ $capacity }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ $namespace }}
    name: 'rift-var-root-rw-launchpad-0'
  storageClassName: {{ $storageClassName }}
  local:
    path: {{ .mountPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .nodeName }}
{{- end }}
{{- with .Values.storage.manual }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $storageClassName }}-{{ $namespace }}-var-root-pv-new
  namespace: {{ $namespace }}
  labels:
    type: local
spec:
  storageClassName: {{ $storageClassName }}
  capacity:
    storage: {{ $capacity }}
  claimRef:
    namespace: {{ $namespace }}
    name: 'rift-var-root-rw-launchpad-0'
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .mountPath }}
{{- end }}
{{- with .Values.storage.nfs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $storageClassName }}-{{ $namespace }}-var-root-pv-new
  namespace: {{ $namespace }}
spec:
  capacity:
    storage: {{ $capacity }}
  claimRef:
    namespace: {{ $namespace }}
    name: 'rift-var-root-rw-launchpad-0'
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
  - hard
  - nfsvers=3.0
  nfs:
    path: {{ .mountPath }}
    server: {{ .server }}
{{- end }}
