# Copyright 2020 RIFT Inc
apiVersion: v1
kind: ConfigMap
metadata:
  name: rw-redis-config
  namespace: {{ .Values.global.namespace.name }}
data:
  rw-redis.conf: |
    appendonly yes
    save 60 100
    dir /data
