# Copyright 2020 RIFT Inc
# Copyright 2021-2022 DZS Inc
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rw-redis
  namespace: {{ .Values.global.namespace.name }}
  labels:
    app: rw.redis
spec:
  replicas: 1
  serviceName: {{ include "redis.fullname" . }}
  selector:
    matchLabels:
      app: rw.redis
  template:
    metadata:
      labels:
        app: rw.redis
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        {{ if .Values.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{ else }}
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
        {{- end }}

      hostAliases:
      {{- range $i, $value := .Values.global.hostAliases }}
      - ip: {{ $value.ip | quote }}
        hostnames:
        {{- range $value.hostnames }}
        - {{ . }}
        {{- end }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        runAsUser: {{ .Values.containerSecurityContext.runAsUser }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
      - name: redis-pl-perm
        image: {{ .Values.busybox.image.repository }}
        imagePullPolicy: {{ .Values.busybox.image.pullPolicy | quote }}
        command: ["chown", "-R", "{{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}", /data]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false

      containers:
        - name: redtunnel
          image: "{{ .Values.redTunnel.image.repository }}:{{ .Values.redTunnel.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redTunnel.image.pullPolicy }}
          command: ["python3", "/rift/redtunnel/redtunnel.py"]
          env:
          - name: RW_K8S_NAMESPACE
            value: {{ .Values.global.namespace.name }}

          volumeMounts:
          - name: tls-cert
            mountPath: /etc/ssl/rw

        - name: redis-exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}

          ports:
           - name: rwredis-exp
             containerPort: 9121
             protocol: TCP

          command:
          - /redis_exporter

        - name: redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: rwredis
              containerPort: 6379
              protocol: TCP

          command:
          - redis-server
          args:
            - '/config/rw-redis.conf'

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
          - name: data
            mountPath: /data
            readOnly: false
          - name: rw-redis-config
            mountPath: /config
            readOnly: false

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: rw-redis-config
          configMap:
            name: rw-redis-config
        - name: tls-cert
          secret:
            secretName: rw-tls-secret
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.redisStorage.capacity }}
      storageClassName: {{ .Values.redisStorage.storageClassName }}
