# Copyright 2020 RIFT Inc
#
{{ $ca := genCA "RIFT" 365 }}
{{ $cn := printf "rift.lp.com" .Release.Namespace }}
{{- if .Values.externalAddress }}
{{ $cn = printf .Values.externalAddress .Release.Namespace }}
{{- end }}
{{ $server := genSignedCert $cn nil nil 365 $ca }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: rw-tls-secret
  namespace: {{ .Values.global.namespace.name }}
data:
  tls.crt: {{ b64enc $server.Cert }}
  tls.key: {{ b64enc $server.Key }}
