# Copyright 2020 RIFT Inc
# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""
prometheusfullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 489

containerSecurityContext:
  runAsUser: 489
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true

prometheus:
  image:
    repository: artifactory.riftio.com/quay.io/prometheus/prometheus
    tag: v2.20.0-rc.1
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []
  capabilities: []
  service:
    type: ClusterIP
  ports:
    rwprom: 9090
  coreDir: null

  busybox:
    image:
      repository: artifactory.riftio.com/docker-hub/busybox
      pullPolicy: IfNotPresent

  configWatch:
    image:
      repository: artifactory.riftio.com/docker-hub/weaveworks/watch
      tag: "master-5b2a6e5"
      pullPolicy: IfNotPresent

# Hostname or IP address through which launchpad can be externally accessed
# This value is mandatory except if service type is "LoadBalancer"
externalAddress: null

imagePullSecrets: []

prometheusStorage:
  storageClassName: null
  capacity: 80Gi
  localStore: {}
  manual: {}
  nfs: {}
