# Copyright 2020 RIFT Inc
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-provision
  namespace: {{ .Values.global.namespace.name }}
data:
  all.yml: |
    # Copyright 2020 RIFT Inc
    - name: 'RIFT'       # name of this dashboard configuration (not dashboard itself)
      org_id: 1          # id of the org to hold the dashboard
      folder: ''         # name of the folder to put the dashboard (http://docs.grafana.org/v5.0/reference/dashboard_folders/)
      folderUid: ''
      type: 'file'       # type of dashboard description (json files)
      options:
        path: '/config/dashboards'       # where dashboards are
        foldersFromFilesStructure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-provision
  namespace: {{ .Values.global.namespace.name }}
data: ~
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Values.global.namespace.name }}
data: ~
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboards
  namespace: {{ .Values.global.namespace.name }}
data:
{{ (.Files.Glob "rw_dashboard/*").AsConfig | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-dashboard
  namespace: {{ .Values.global.namespace.name }}
data:
  dashboard.json: |
    {
      "links": [],
      "panels": [
        {
          "datasource": null,
          "folderId": 0,
          "gridPos": {
            "h": 15,
            "w": 12,
            "x": 0,
            "y": 4
          },
          "headings": true,
          "id": 3,
          "limit": 30,
          "links": [],
          "options": {},
          "query": "",
          "recent": true,
          "search": false,
          "starred": true,
          "tags": [],
          "title": "Dashboards",
          "type": "dashlist"
        }
      ],
      "schemaVersion": 22,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "hidden": true,
        "refresh_intervals": ["5s", "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d"],
        "time_options": ["5m", "15m", "1h", "6h", "12h", "24h", "2d", "7d", "30d"],
        "type": "timepicker"
      },
      "timezone": "browser",
      "title": "RIFT Home"
    }
