apiVersion: v2
appVersion: 10.1.2
dependencies:
- name: alertmgr
  repository: file://./charts/alertmgr
  version: 0.21.0
- name: prometheus
  repository: file://./charts/prometheus
  version: 2.20.0
- name: grafana
  repository: file://./charts/grafana
  version: 1.2.0
- condition: loki.enabled
  name: loki
  repository: file://./charts/loki
  version: 1.6.0
- name: redis
  repository: file://./charts/redis
  version: 6.0.8
- name: nats
  repository: file://./charts/nats
  version: 2.1.8
- name: mongodb
  repository: file://./charts/mongodb
  version: 4.4.1
- name: haproxy-ingress
  repository: file://./charts/haproxy-ingress
  version: "0.1"
description: A Helm chart for RIFT.ware Launchpad
name: launchpad
type: application
version: 10.1.2
