# Copyright 2020 RIFT Inc
# Copyright 2021 DZS Inc
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ingress-default-backend
  name: rw-haproxy-default-backend
  namespace: {{ .Values.global.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ingress-default-backend
  template:
    metadata:
      labels:
        run: ingress-default-backend
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        {{ if .Values.image.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{ else }}
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
        {{- end }}
      containers:
        - name: ingress-default-backend
          image: {{ .Values.defaultbackend.image.repository -}} : {{- .Values.defaultbackend.image.tag }}
          imagePullPolicy: {{ .Values.defaultbackend.image.pullPolicy }}
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ingress-default-backend
  name: ingress-default-backend
  namespace: {{ .Values.global.namespace.name }}
spec:
  selector:
    run: ingress-default-backend
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
